### ISSUE TITLE
Intermittent failure to resize the dropdown view after calling spinner.setItems(choices);

### ISSUE THREAD

**Issue by mikebikemusic** [skydoves/PowerSpinner#32]
**Please complete the following information:**
- Library Version v1.1.0 and maybe 1.0.9
- Affected Device(s) emulator and devices
 
**Describe the Bug:**
This is an intermittent bug. I didn't see it for a whole day and then today it started happening. I built the simplest test case. The simple test case failed for about an hour, then I changed some parameters to show the scroll case (count = 3 and pos = 2) and it stopped failing. I set it back and it wasn't failing. I switched between library 1.0.9 and 1.1.0 and the bug returned.

        spinner.setDismissWhenNotifiedItemSelected(false);

When spinner.setItems is called with a different number of items, (by pressing the one, two, three choices) the popup list sometimes does not change in size. If the list grows, you have to scroll to see the rest. If the list shrinks, there is a blank space after the last item.  Fortunately, I have screen shots of both cases.

Steps to reproduce:
1. Run the attached app in simulator. Defaults to 5 choices.
2. Select one should shrink to two choices without extra white space below.
If it fails it will never fix itself during the same app run. If it succeeds it wont'f fail during the same app run.

**Expected Behavior:**

The list should always dynamically change. I sent you a video yesterday when it was behaving correctly.  Attaching project files and screenshots.

[MyApplication4.zip](https://github.com/skydoves/PowerSpinner/files/4950983/MyApplication4.zip)
<img width="405" alt="Screen Shot 2020-07-20 at 7 32 35 PM" src="https://user-images.githubusercontent.com/4509918/88006763-4ac2ca00-cac1-11ea-92e6-a53e43484036.png">
<img width="409" alt="Screen Shot 2020-07-20 at 5 58 07 PM" src="https://user-images.githubusercontent.com/4509918/88006773-50b8ab00-cac1-11ea-9132-ba4fb677976b.png">
<img width="402" alt="Screen Shot 2020-07-20 at 7 30 57 PM" src="https://user-images.githubusercontent.com/4509918/88006784-5615f580-cac1-11ea-8933-8c655889f1d2.png">

**Comment by skydoves** [comment]
Fixed: https://github.com/skydoves/PowerSpinner/releases/tag/1.1.1

**Comment by dol-mimo** [comment]
Hello, I am still facing this issue. I am using the latest version 1.2.7
What should I do?
```
<com.skydoves.powerspinner.PowerSpinnerView
                android:id="@+id/select_category_name"
                style="@style/style_1"
                android:hint="@string/select_category"
                app:spinner_arrow_gravity="end"
                app:spinner_arrow_padding="0dp"
                app:spinner_arrow_tint="@color/color_gray_217"
                app:spinner_divider_color="#D5D8DB"
                app:spinner_divider_show="true"
                app:spinner_popup_animation="dropdown"
                app:spinner_popup_background="@color/white"
                app:spinner_popup_elevation="5dp" />
```
